### PR TITLE
Miscellaneous fixes

### PR DESCRIPTION
**Pull request by Yukinoroh**
Added decomposition info for U+8001(老)
AJ1-04248 is in Unicode; changed to U+51F5 (凵)
AJ1-05368 is in Unicode; changed to U+6BCB (毋)
AJ1-14094 is in Unicode; changed to U+7C7B (类)
AJ1-14496 is in Unicode; changed to U+5DF8 (巸)
Fixed and improved duplicate references to ⿱⺈旧
　&GT-K03616; -> ⿱⺈旧
　&GT-K03318; -> ⿱⺈旧

Other than that I noticed two references to the same parts: &A-GT-K0605; and &GT-K0605; 
Not sure what the differences are.

### CODE REVIEW

**Review by chise — CHANGES_REQUESTED** [review]
It introduces a bug.

**Comment by Yukinoroh** [comment]
What bug is it?

**Comment by Yukinoroh** [comment]
What bug is it? どこが問題になりますか。

**Comment by chise** [comment]
It had already been reverted.
I had overlooked https://github.com/chise/ids/pull/14/commits/b0114e17e73423940a3c538e139c26f6b2250e4e.

**Pull request closed without merging**
