### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Yukinoroh**
・U+89B3: Use "𮥶" instead of "⿳𠂉&CDP-88F1;&CDP-8965;"
・U+61D0: fix following pattern of U+58CA.
・U+2AF9D, U+31CA2: Use "𱘥" instead of "⿳⿶凵米八夊"
・U+6B6F, U+20D91, U+214CC, U+23C65, U+2A92B, U+2AD95, U+2C1C8, U+31625, U+31E38: Use "𱐍" instead of "⿶凵米"
・U+66FE, U+6703, U+287A4: Use "𭥴" instead of "&CDP-8B63;"
・U+299B3: Use "𥪖" instead of "⿱立&CDP-88E5;"
・U+26A42, U+2CC7D: Use "𭻾" instead of "⿱𠂉疋"

### CODE REVIEW

**Review by chise — COMMENTED** [review]
- &A-GT-K06065;'s structure is ⿱<爫・𫜵>旧, not ⿱⺈旧.  In addition, it has been unified with U+31B39, so it will be converted to UCS automatically.
- Don't use 「⺈」 as an abstract component of abstract characters [please preserve &(A-)GT-K03616;]

**Comment by Yukinoroh** [comment]
Thanks for letting me know about the unification with U+31B39.

What is the difference between GT-K03616 and GT-K03618?
What is an abstract character?

**Comment by Yukinoroh** [comment]
I reverted the abstract characters and added another change.
Let me know of any problem.

**Comment by chise** [comment]
> Thanks for letting me know about the unification with U+31B39.
> 
> What is the difference between GT-K03616 and GT-K03618? What is an abstract character?

GT-K03616: https://www.chise.org/est/view/character/rep.gt-k=03616 (⿱𠂊旧)
GT-K03318: https://www.chise.org/est/view/character/rep.gt-k=03318 (⿱GT-K00089旧)
<GT-K03318>: https://www.chise.org/est/view/character/a.gt-k=03318 (⿱<刀/𠂊><旧>)

An abstract character unifies glyphs.  GT-K03616 and GT-K03318 are glyphs
(In the current definition of the CHISE character ontology, GT-K03616's granularity is abstract glyph,
and GT-K03318's granularity is detailed glyph).
Abstract character <GT-K03318> unifies GT-K03318 and GT-K03318 unifies GT-K03616.

In the current definition of the CHISE character ontology, <CJK RADICAL KNIFE ONE> is regarded as a glyph,
not an abstract character.

**Comment by Yukinoroh** [comment]
What was the problem with this pull request?

**Comment by chise** [comment]
This PR was large and including multiple issues, and another changes were added whilte I was reviewing, then the PR conflicted with my working set, so I applied it manually.  I think I applied all acceptable changes of the PR.  I did this manually so sorry if I missed something.

**Comment by Yukinoroh** [comment]
Thanks. I checked, it looks all right.
This database is really helping my current work, so I thought of improving it.

**Pull request closed without merging**
